import { useState, useEffect, useMemo } from "react";
import {
  FaGraduationCap,
  FaAward,
  FaRegFileAlt,
  FaClipboardCheck,
  FaSearch,
  FaEye,
  FaPlus,
  FaCalendarAlt,
} from "react-icons/fa";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { toast } from "sonner";
import axios from "axios";
import { FiAward } from "react-icons/fi";
import { LuFileCheck } from "react-icons/lu";
import { FiDownload } from "react-icons/fi";

const API_BASE = "https://lauratek.in:8000/trainer";

export default function Certificates() {
  const [generatingBulk, setGeneratingBulk] = useState(false);
  const [generatingSingle, setGeneratingSingle] = useState(false);
  const [selectedCert, setSelectedCert] = useState<any>(null);
  const [refreshTrigger, setRefreshTrigger] = useState(0);

  const [bulkCourseId, setBulkCourseId] = useState<string>("");
  const [bulkStudentIds, setBulkStudentIds] = useState<string>("");

  const [manualStudentId, setManualStudentId] = useState<string>("");
  const [manualCourseId, setManualCourseId] = useState<string>("");

  const token = localStorage.getItem("access_token");

  const axiosInstance = axios.create({
    baseURL: API_BASE,
    headers: {
      Authorization: token ? `Bearer ${token}` : "",
      "Content-Type": "application/json",
    },
  });

  const [courses, setCourses] = useState<any[]>([]);

  useEffect(() => {
    const fetchCoursesList = async () => {
      try {
        const res = await axiosInstance.get("/courses");
        const coursesData = Array.isArray(res.data) ? res.data : [];
        setCourses(coursesData);
        if (coursesData.length > 0) {
          setFilterCourseId(String(coursesData[0].id));
        }
      } catch (err) {
        console.error("Failed to fetch courses list:", err);
      }
    };
    fetchCoursesList();
  }, []);

  const generateSingleCertificate = async () => {
    const studentId = Number(manualStudentId.trim());
    const courseId = Number(manualCourseId.trim());

    if (!studentId || isNaN(studentId) || studentId <= 0) {
      return toast.error("Please enter a valid student ID");
    }
    if (!courseId || isNaN(courseId) || courseId <= 0) {
      return toast.error("Please enter a valid course ID");
    }

    setGeneratingSingle(true);

    try {
      const res = await axiosInstance.post(
        `/students/${studentId}/courses/${courseId}/certificate`
      );

      toast.success(
        res.data?.certificate_no
          ? `Certificate generated: ${res.data.certificate_no}`
          : "Certificate generated successfully!"
      );

      if (res.data?.file_url) {
        toast.info(
          "Certificate generated — you can now download it from student portal",
          { duration: 6000 }
        );
      }

      setManualStudentId("");
      setManualCourseId("");
      setFilterCourseId(String(courseId));
      setRefreshTrigger(prev => prev + 1);
    } catch (err: any) {
      const msg =
        err?.response?.data?.message || "Failed to generate certificate";
      toast.error(msg);
    } finally {
      setGeneratingSingle(false);
    }
  };

  const handleDownload = (studentName: string) => {
    // Generate a mock PDF file blob for demonstration
    const blob = new Blob([`Mock Certificate Data for ${studentName}\nGenerated by Laura Instructor Dashboard.`], { type: 'application/pdf' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Certificate_${studentName.replace(/\s+/g, '_')}.pdf`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
    toast.success(`Successfully downloaded certificate for ${studentName}`);
  };

  const generateBulkCertificates = async () => {
    const courseIdNum = Number(bulkCourseId.trim());

    if (!courseIdNum || isNaN(courseIdNum) || courseIdNum <= 0) {
      return toast.error("Please enter a valid course ID");
    }

    setGeneratingBulk(true);

    try {
      let payload: any = null;

      if (bulkStudentIds.trim()) {
        const studentIds = bulkStudentIds
          .split(",")
          .map((id) => Number(id.trim()))
          .filter((id) => !isNaN(id) && id > 0);

        if (studentIds.length === 0) {
          return toast.error(
            "Invalid student IDs format. Use comma-separated numbers, e.g. 12,15,18"
          );
        }

        payload = { student_ids: studentIds };
      }

      const res = await axiosInstance.post(
        `/courses/${courseIdNum}/certificates/bulk`,
        payload
      );

      toast.success(
        `Requested: ${res.data?.requested || res.data?.total || 0} | ` +
        `Generated: ${res.data?.generated || 0} | ` +
        `Skipped: ${res.data?.skipped || res.data?.existing || 0}`
      );

      setBulkCourseId("");
      setBulkStudentIds("");
      setFilterCourseId(String(courseIdNum));
      setRefreshTrigger(prev => prev + 1);
    } catch (err: any) {
      console.error("Bulk generation failed:", err?.response?.data || err);

      const errorDetail = err?.response?.data;
      let msg = "Bulk generation failed";

      if (errorDetail?.detail) {
        msg += ` - ${JSON.stringify(errorDetail.detail)}`;
      } else if (errorDetail?.message) {
        msg += ` - ${errorDetail.message}`;
      } else {
        msg += " (check console for details)";
      }

      toast.error(msg, { duration: 8000 });
    } finally {
      setGeneratingBulk(false);
    }
  };

  const [certificateRows, setCertificateRows] = useState<any[]>([]);
  const [searchTerm, setSearchTerm] = useState<string>("");
  const [filterCourseId, setFilterCourseId] = useState<string>("");
  const [statusFilter, setStatusFilter] = useState<string>("All Status");
  const [totalCertificates, setTotalCertificates] = useState<number>(0);

  const handleResetFilters = () => {
    setSearchTerm("");
    setDate("");
    setStatusFilter("All Status");
    if (courses && courses.length > 0) {
      setFilterCourseId(String(courses[0].id));
    } else {
      setFilterCourseId("");
    }
    setRefreshTrigger(prev => prev + 1);
  };

  useEffect(() => {
    const fetchCertificates = async () => {
      if (!filterCourseId.trim()) {
        setCertificateRows([]);
        setTotalCertificates(0);
        return;
      }
      try {
        const res = await axiosInstance.get(`/courses/${filterCourseId}/certificates`);
        if (res.data && res.data.certificates) {
          const fetchedCerts = res.data.certificates.map((cert: any) => {
            const localDate = (() => {
              if (!cert.issued_at) return "-";
              try {
                const d = new Date(cert.issued_at);
                if (isNaN(d.getTime())) return "-";
                const day = String(d.getDate()).padStart(2, "0");
                const month = String(d.getMonth() + 1).padStart(2, "0");
                const year = d.getFullYear();
                return `${day}/${month}/${year}`;
              } catch {
                return "-";
              }
            })();

            return {
              initials: cert.student_name ? cert.student_name.substring(0, 2).toUpperCase() : "NA",
              name: cert.student_name,
              studentId: cert.student_id.toString(),
              courseId: res.data.course_id.toString(),
              certificateNo: cert.certificate_no || "-",
              date: localDate,
              status: cert.status === "valid" ? "Issued" : "Pending",
              download_url: cert.download_url,
            };
          });

          setCertificateRows(fetchedCerts);
          setTotalCertificates(res.data.total_certificates || 0);
        } else {
          setTotalCertificates(0);
        }
      } catch (err: any) {
        setCertificateRows([]);
        setTotalCertificates(0);
        const errorMsg = err?.response?.data?.detail || err?.response?.data?.message || "Failed to fetch certificates";
        toast.error(errorMsg);
        console.error("Failed to fetch certificates:", err);
      }
    };

    // Add debounce to prevent too many API calls
    const timeoutId = setTimeout(() => {
      fetchCertificates();
    }, 500);

    return () => clearTimeout(timeoutId);
  }, [filterCourseId, refreshTrigger]);
  const [date, setDate] = useState("");

  const handleDateChange = (e) => {
    let value = e.target.value.replace(/\D/g, ""); // Only numbers

    // Allow only 8 digits (DDMMYYYY)
    if (value.length > 8) {
      value = value.slice(0, 8);
    }

    // Auto format as DD/MM/YYYY
    if (value.length > 4) {
      value = `${value.slice(0, 2)}/${value.slice(2, 4)}/${value.slice(4)}`;
    } else if (value.length > 2) {
      value = `${value.slice(0, 2)}/${value.slice(2)}`;
    }

    setDate(value);
  };

  const thisMonthCertificatesCount = useMemo(() => {
    const currentMonth = new Date().getMonth();
    const currentYear = new Date().getFullYear();

    return certificateRows.filter(cert => {
      if (cert.date && cert.date !== "-") {
        const parts = cert.date.split("/");
        if (parts.length === 3) {
          const month = Number(parts[1]) - 1; // 0-indexed month
          const year = Number(parts[2]);
          return month === currentMonth && year === currentYear;
        }
      }
      return false;
    }).length;
  }, [certificateRows]);

  const filteredCerts = useMemo(() => {
    return certificateRows.filter(row => {
      const matchesSearch = !searchTerm.trim() ||
        (row.name && row.name.toLowerCase().includes(searchTerm.toLowerCase())) ||
        (row.studentId && row.studentId.includes(searchTerm)) ||
        (row.certificateNo && row.certificateNo.toLowerCase().includes(searchTerm.toLowerCase()));

      const matchesDate = !date || row.date === date;
      const matchesStatus = statusFilter === "All Status" || row.status === statusFilter;

      return matchesSearch && matchesDate && matchesStatus;
    });
  }, [certificateRows, searchTerm, date, statusFilter]);

  return (
    <div className="w-full min-h-screen bg-[#F8FAFC] p-2 md:p-3 overflow-x-hidden">
      <div className="w-full w-full">
        <div className="mb-6 sm:mb-8">
          <div className="flex items-center gap-3 mb-1">
            {/* <FaGraduationCap className="w-8 h-8 sm:w-9 sm:h-9 text-blue-600 shrink-0" /> */}
            <h1 className="text-2xl sm:text-3xl font-bold text-gray-900">
              Certificates
            </h1>
          </div>

          <p className="text-gray-500 text-base">
            Manage and issue course certificates
          </p>
        </div>

        <div className="grid grid-cols-2 xl:grid-cols-4 gap-4 sm:gap-6 mb-8">
          <div className="bg-white shadow-md border border-gray-200 rounded-[20px] px-5 py-6  flex items-start justify-between min-h-[118px]">
            <div>
              <p className="text-xs sm:text-sm text-gray-500 mb-1.5 font-medium">
                Total Issued
              </p>
              <p className="text-xl sm:text-3xl font-bold text-gray-900">
                {totalCertificates.toLocaleString()}
              </p>
            </div>
            <FiAward className="h-4 w-4 sm:h-5 sm:w-5 text-blue-600 shrink-0 mt-0.5" />
          </div>

          <div className="bg-white shadow-md border border-gray-200 rounded-[20px] px-5 py-6  flex items-start justify-between min-h-[118px]">
            <div>
              <p className="text-xs sm:text-sm text-gray-500 mb-1.5 font-medium">
                This Month
              </p>
              <p className="text-xl sm:text-3xl font-bold text-green-600">
                {thisMonthCertificatesCount.toLocaleString()}
              </p>
            </div>
            <LuFileCheck className="h-4 w-4 sm:h-5 sm:w-5 text-green-600 shrink-0 mt-0.5" />
          </div>

        </div>

        <Card className="mb-6 sm:mb-8 rounded-[20px] border border-gray-200 shadow-sm">
          <CardHeader className="pb-3 flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
            <div>
              <CardTitle className="text-xl sm:text-2xl font-bold text-gray-900">
                Generate Single Certificate
              </CardTitle>
              <CardDescription className="text-gray-500 mt-1">
                Manually issue certificate for one student (useful for testing /
                corrections)
              </CardDescription>
            </div>

            <Button
              onClick={generateSingleCertificate}
              disabled={
                generatingSingle ||
                !manualStudentId.trim() ||
                !manualCourseId.trim()
              }
              className="w-full sm:w-auto min-w-[220px] h-12 rounded-xl bg-gradient-to-r from-blue-600 to-purple-600 text-white hover:from-blue-700 hover:to-purple-700 flex items-center justify-center gap-2"
            >
              <FaPlus className="h-4 w-4" />
              {generatingSingle ? "Generating..." : "Generate Certificate"}
            </Button>
          </CardHeader>

          <CardContent className="grid grid-cols-1 sm:grid-cols-2 gap-5">
            <div>
              <Label htmlFor="studentId" className="mb-2 block text-gray-900">
                Student ID
              </Label>
              <Input
                id="studentId"
                type="text"
                inputMode="numeric"
                placeholder="Enter Student ID"
                value={manualStudentId}
                maxLength={6}
                onChange={(e) => setManualStudentId(e.target.value.replace(/\D/g, ""))}
                className="h-12 rounded-xl bg-gray-50 border-gray-200"
              />
            </div>

            <div>
              <Label
                htmlFor="courseIdManual"
                className="mb-2 block text-gray-900"
              >
                Course ID
              </Label>
              <Input
                id="courseIdManual"
                type="text"
                inputMode="numeric"
                placeholder="Enter Course ID"
                value={manualCourseId}
                maxLength={6}
                onChange={(e) => setManualCourseId(e.target.value.replace(/\D/g, ""))}
                className="h-12 rounded-xl bg-gray-50 border-gray-200"
              />
            </div>
          </CardContent>
        </Card>

        <Card className="mb-6 sm:mb-8 rounded-2xl border border-gray-200 shadow-sm">
          <CardHeader className="pb-3 flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
            <div>
              <CardTitle className="text-xl sm:text-2xl font-bold text-gray-900">
                Bulk Generate Certificates
              </CardTitle>
              <CardDescription className="text-gray-500 mt-1">
                Generate certificates for an entire course (or selected students)
                — trainer/admin only
              </CardDescription>
            </div>

            <Button
              onClick={generateBulkCertificates}
              disabled={generatingBulk || !bulkCourseId.trim()}
              className="w-full sm:w-auto min-w-[190px] h-12 rounded-xl bg-gradient-to-r from-blue-600 to-purple-600 text-white hover:from-blue-700 hover:to-purple-700 flex items-center justify-center gap-2"
            >
              <FaPlus className="h-4 w-4" />
              {generatingBulk ? "Generating..." : "Generate Bulk"}
            </Button>
          </CardHeader>

          <CardContent className="grid grid-cols-1 sm:grid-cols-2 gap-5">
            <div>
              <Label
                htmlFor="studentIdsBulk"
                className="mb-2 block text-gray-900"
              >
                Student ID
              </Label>
              <Input
                id="studentIdsBulk"
                type="text"
                inputMode="numeric"
                value={bulkStudentIds}
                maxLength={6}
                onChange={(e) => setBulkStudentIds(e.target.value.replace(/\D/g, ""))}
                placeholder="Enter Student ID"
                className="h-12 rounded-xl bg-gray-50 border-gray-200"
              />
            </div>

            <div>
              <Label htmlFor="courseIdBulk" className="mb-2 block text-gray-900">
                Course ID
              </Label>
              <Input
                id="courseIdBulk"
                type="text"
                inputMode="numeric"
                value={bulkCourseId}
                maxLength={6}
                onChange={(e) => setBulkCourseId(e.target.value.replace(/\D/g, ""))}
                placeholder="Enter Course ID"
                className="h-12 rounded-xl bg-gray-50 border-gray-200"
              />
            </div>
          </CardContent>
        </Card>

        {/* Filters & Search */}
        <div className="bg-white rounded-[24px] p-7 shadow-sm border border-gray-200 mb-6 sm:mb-8">
          <div className="flex items-center gap-3.5 mb-6">
            <div className="p-3 bg-gradient-to-r from-blue-600 to-purple-600 rounded-[14px]">
              <FaSearch className="w-5 h-5 text-white" />
            </div>
            <div>
              <h3 className="font-bold text-gray-900 text-[18px]">Filters & Search</h3>
              <p className="text-[13px] text-gray-400 font-medium mt-0.5">Refine your certificate list</p>
            </div>
          </div>

          <div className="flex flex-col lg:flex-row gap-y-4 gap-x-4 items-center">
            {/* Search - Flexible width */}
            <div className="relative w-full lg:flex-1">
              <FaSearch className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400 w-4 h-4" />
              <input
                type="text"
                placeholder="Search certificates..."
                value={searchTerm}
                maxLength={20}
                onChange={(e) => {
                  const val = e.target.value;
                  if (/^[a-zA-Z\s]*$/.test(val)) {
                    setSearchTerm(val);
                  }
                }}
                className="w-full pl-11 pr-4 py-3.5 border border-gray-200 rounded-xl bg-[#F9FAFB] focus:outline-none focus:ring-0 focus:border-gray-200 focus:bg-white transition-colors text-sm font-medium placeholder:text-gray-400"
              />
            </div>

            {/* Right Side Group */}
            <div className="flex flex-wrap sm:flex-nowrap items-center gap-3 w-full lg:w-auto">
              <div className="relative flex-1 sm:flex-none w-full sm:w-40 md:w-48 lg:w-40 xl:w-48">
                <select
                  value={filterCourseId}
                  onChange={(e) => setFilterCourseId(e.target.value)}
                  className="w-full pl-4 pr-10 py-3.5 border border-gray-200 rounded-xl bg-[#F9FAFB] focus:outline-none focus:ring-0 focus:border-gray-200 focus:bg-white transition-colors text-sm font-medium text-gray-700 appearance-none cursor-pointer"
                >
                  <option value="">Select Course</option>
                  {courses.map((course) => {
                    const title = course.title || course.name || `Course #${course.id}`;
                    const displayTitle = title.length > 25 ? title.substring(0, 25) + "..." : title;
                    return (
                      <option key={course.id} value={course.id.toString()}>
                        {displayTitle} (ID: {course.id})
                      </option>
                    );
                  })}
                </select>
                <div className="absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none text-gray-400">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-chevron-down"><path d="m6 9 6 6 6-6" /></svg>
                </div>
              </div>

              <div className="relative flex-1 sm:flex-none w-full sm:w-40 md:w-48 lg:w-40 xl:w-48">
                <input
                  type="text"
                  value={date}
                  onChange={handleDateChange}
                  placeholder="dd/mm/yyyy"
                  maxLength={10}
                  inputMode="numeric"
                  className="w-full pl-4 pr-10 py-3.5 border border-gray-200 rounded-xl bg-[#F9FAFB] focus:outline-none focus:ring-0 focus:border-gray-200 focus:bg-white transition-colors text-sm font-medium text-gray-600"
                />
                <FaCalendarAlt className="absolute right-4 top-1/2 -translate-y-1/2 text-gray-400 w-4 h-4" />
              </div>

              <div className="relative flex-1 sm:flex-none w-full sm:w-40 md:w-48 lg:w-40 xl:w-48">
                <select
                  value={statusFilter}
                  onChange={(e) => setStatusFilter(e.target.value)}
                  className="w-full pl-4 pr-10 py-3.5 border border-gray-200 rounded-xl bg-[#F9FAFB] focus:outline-none focus:ring-0 focus:border-gray-200 focus:bg-white transition-colors text-sm font-medium text-gray-600 appearance-none cursor-pointer"
                >
                  <option value="All Status">All Status</option>
                  <option value="Issued">Issued</option>
                  <option value="Pending">Pending</option>
                </select>
                <div className="absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none text-gray-400">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="lucide lucide-chevron-down"><path d="m6 9 6 6 6-6" /></svg>
                </div>
              </div>

              <button
                type="button"
                onClick={handleResetFilters}
                className="flex items-center justify-center gap-2 px-8 py-3.5 border border-gray-200 rounded-xl bg-[#F9FAFB] hover:bg-gray-50 text-gray-600 text-sm font-bold transition-all whitespace-nowrap min-w-[130px] w-full sm:w-auto"
              >
                Reset
              </button>
            </div>
          </div>
        </div>

        <div className="hidden md:block bg-white border border-gray-200 rounded-xl shadow-sm mb-8 overflow-hidden">
          <div className="overflow-x-auto">
            <table className="min-w-[850px] w-full text-left text-sm">
              <thead>
                <tr className="border-b border-gray-100 text-gray-900">
                  <th className="py-5 px-6 font-semibold">Student</th>
                  <th className="py-5 px-6 font-semibold">Student ID</th>
                  <th className="py-5 px-6 font-semibold">Course ID</th>
                  <th className="py-5 px-6 font-semibold">Certificate No</th>
                  <th className="py-5 px-6 font-semibold">Issue Date</th>
                  <th className="py-5 px-6 font-semibold">Status</th>
                  <th className="py-5 px-6 font-semibold text-right">
                    Actions
                  </th>
                </tr>
              </thead>

              <tbody className="divide-y divide-gray-100">
                {filteredCerts.length === 0 ? (
                  <tr>
                    <td colSpan={7} className="py-8 text-center text-gray-500">
                      No certificates found.
                    </td>
                  </tr>
                ) : (
                  filteredCerts.map((row, idx) => (
                    <tr key={`${row.studentId}-${idx}`}>
                      <td className="py-5 px-6">
                        <div className="flex items-center gap-3">
                          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-blue-500 to-purple-600 text-white text-sm font-semibold flex items-center justify-center shrink-0">
                            {row.initials}
                          </div>
                          <span className="font-medium text-gray-900">
                            {row.name}
                          </span>
                        </div>
                      </td>

                      <td className="py-5 px-6 text-gray-600 font-mono">
                        {row.studentId}
                      </td>

                      <td className="py-5 px-6 text-gray-600 font-mono">
                        {row.courseId}
                      </td>

                      <td className={`py-5 px-6 font-bold text-gray-700`}>
                        {row.certificateNo}
                      </td>

                      <td className="py-5 px-6 text-gray-600">{row.date}</td>

                      <td className="py-5 px-6">
                        <span
                          className={`inline-flex items-center px-3 py-1 rounded-full text-xs font-medium ${row.status === "Issued"
                            ? "bg-green-50 text-green-600"
                            : "bg-orange-50 text-orange-500"
                            }`}
                        >
                          {row.status}
                        </span>
                      </td>

                      <td className="py-5 px-6 text-right">
                        <div className="flex items-center justify-end gap-3">
                          {row.status === "Issued" ? (
                            <>
                              <button
                                onClick={() => setSelectedCert(row)}
                                className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-blue-50 text-blue-600 text-sm hover:bg-blue-100"
                              >
                                <FaEye className="h-3.5 w-3.5" />
                                View
                              </button>

                              {row.download_url ? (
                                <a
                                  href={row.download_url}
                                  target="_blank"
                                  rel="noopener noreferrer"
                                  className="p-2 text-gray-500 hover:text-gray-700"
                                >
                                  <FiDownload className="h-4 w-4 text-gray-800" />
                                </a>
                              ) : (
                                <button
                                  onClick={() => handleDownload(row.name)}
                                  className="p-2 text-gray-500 hover:text-gray-700"
                                >
                                  <FiDownload className="h-4 w-4 text-gray-800" />
                                </button>
                              )}
                            </>
                          ) : (
                            <button className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-gradient-to-r from-blue-600 to-purple-600 text-white text-sm hover:from-blue-700 hover:to-purple-700">
                              <FaAward className="h-3.5 w-3.5" />
                              Issue
                            </button>
                          )}
                        </div>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>

        <div className="md:hidden space-y-3 mb-8">
          {filteredCerts.length === 0 ? (
            <div className="bg-white border border-gray-200 rounded-xl shadow-sm p-6 text-center text-gray-500">
              No certificates found.
            </div>
          ) : (
            filteredCerts.map((row, idx) => (
              <div
                key={`${row.studentId}-${idx}`}
                className="bg-white border border-gray-200 rounded-xl shadow-sm p-4"
              >
                <div className="flex items-start justify-between gap-3 mb-4">
                  <div className="flex items-center gap-3 min-w-0">
                    <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-blue-500 to-purple-600 text-white text-xs font-semibold flex items-center justify-center shrink-0">
                      {row.initials}
                    </div>

                    <div className="min-w-0">
                      <p className="font-semibold text-gray-900 truncate">
                        {row.name}
                      </p>
                      <p className="text-xs text-gray-500 truncate">
                        {row.studentId}
                      </p>
                    </div>
                  </div>

                  <span
                    className={`shrink-0 inline-flex items-center px-3 py-1 rounded-full text-xs font-medium ${row.status === "Issued"
                      ? "bg-green-50 text-green-600"
                      : "bg-orange-50 text-orange-500"
                      }`}
                  >
                    {row.status}
                  </span>
                </div>

                <div className="grid grid-cols-2 gap-3 text-xs mb-4">
                  <div>
                    <p className="text-gray-400">Course ID</p>
                    <p className="font-medium text-gray-700 break-words">
                      {row.courseId}
                    </p>
                  </div>

                  <div>
                    <p className="text-gray-400">Certificate No</p>
                    <p className={`font-bold text-gray-700`}>{row.certificateNo}</p>
                  </div>

                  <div>
                    <p className="text-gray-400">Issue Date</p>
                    <p className="font-medium text-gray-700">{row.date}</p>
                  </div>

                  <div>
                    <p className="text-gray-400">Action</p>
                    {row.status === "Issued" ? (
                      <div className="flex items-center gap-2 mt-1">
                        <button
                          onClick={() => setSelectedCert(row)}
                          className="inline-flex items-center gap-1 px-3 py-1.5 rounded-full bg-blue-50 text-blue-600 text-xs hover:bg-blue-100"
                        >
                          <FaEye className="h-3.5 w-3.5" />
                          View
                        </button>
                        {row.download_url ? (
                          <a
                            href={row.download_url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="p-1.5 text-gray-500 hover:text-gray-700"
                          >
                            <FiDownload className="h-4 w-4" />
                          </a>
                        ) : (
                          <button
                            onClick={() => handleDownload(row.name)}
                            className="p-1.5 text-gray-500 hover:text-gray-700"
                          >
                            <FiDownload className="h-4 w-4" />
                          </button>
                        )}
                      </div>
                    ) : (
                      <button className="inline-flex items-center gap-1 px-3 py-1.5 rounded-full bg-gradient-to-r from-blue-600 to-purple-600 text-white text-xs mt-1">
                        <FaAward className="h-3.5 w-3.5" />
                        Issue
                      </button>
                    )}
                  </div>
                </div>
              </div>
            ))
          )}
        </div>

        {/* Certificate View Modal */}
        {selectedCert && (
          <div className="fixed inset-0 z-[100] bg-black/60 p-4 sm:p-6 overflow-y-auto flex flex-col">
            <div className="bg-white border border-gray-200 rounded-2xl shadow-2xl p-4 sm:p-5 w-full max-w-3xl relative animate-in fade-in zoom-in-95 duration-200 flex flex-col my-auto mx-auto shrink-0">

              {/* Header */}
              <div className="flex items-start sm:items-center justify-between mb-3 shrink-0 gap-4">
                <h3 className="text-lg sm:text-xl font-bold text-gray-900 mt-1 sm:mt-0">
                  Certificate Preview - <span className="break-words">{selectedCert.name}</span>
                </h3>
                <button
                  onClick={() => setSelectedCert(null)}
                  className="p-1.5 bg-gray-50 hover:bg-gray-100 border border-gray-200 rounded-full text-gray-500 hover:text-gray-700 transition-colors shrink-0"
                >
                  <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="sm:w-5 sm:h-5"><path d="M18 6 6 18" /><path d="m6 6 12 12" /></svg>
                </button>
              </div>

              {/* Certificate Body */}
              <div className="bg-gradient-to-br from-[#F8FAFC] to-[#F1F5F9] rounded-xl sm:rounded-2xl border border-gray-200 p-4 sm:p-6 md:p-8 text-center shadow-sm shrink-0">
                <FaAward className="h-10 w-10 sm:h-12 sm:w-12 text-blue-600 mx-auto mb-2 sm:mb-3 drop-shadow-sm" />

                <h2 className="text-xl sm:text-2xl md:text-3xl font-extrabold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent mb-2 tracking-tight leading-tight">
                  Certificate of Completion
                </h2>

                <p className="text-gray-500 text-xs sm:text-sm mb-2 sm:mb-3 font-medium leading-tight">
                  This is to certify that
                </p>

                <p className="text-lg sm:text-2xl font-bold text-gray-900 mb-2 sm:mb-3 break-words leading-tight">
                  {selectedCert.name}
                </p>

                <p className="text-gray-500 text-xs sm:text-sm mb-2 sm:mb-3 font-medium leading-tight">
                  has successfully completed
                </p>

                <p className="text-base sm:text-xl font-bold text-gray-900 mb-4 sm:mb-5 break-words leading-tight">
                  {selectedCert.courseId}
                </p>

                <div className="border-t border-gray-200 pt-3 sm:pt-4">
                  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 sm:gap-4 text-xs sm:text-sm">
                    <div className="bg-white/50 sm:bg-transparent p-2 sm:p-0 rounded-lg">
                      <p className="text-gray-500 mb-0.5 font-medium">Issue Date</p>
                      <p className="font-bold text-gray-900">{selectedCert.date}</p>
                    </div>

                    <div className="bg-white/50 sm:bg-transparent p-2 sm:p-0 rounded-lg">
                      <p className="text-gray-500 mb-0.5 font-medium">Student ID</p>
                      <p className="font-bold text-gray-900 break-words">
                        {selectedCert.studentId}
                      </p>
                    </div>

                    <div className="bg-white/50 sm:bg-transparent p-2 sm:p-0 rounded-lg">
                      <p className="text-gray-500 mb-0.5 font-medium">Certificate No</p>
                      <p className="font-bold text-gray-900 break-words">
                        {selectedCert.certificateNo}
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              {/* Footer */}
              <div className="mt-4 flex flex-col sm:flex-row justify-end gap-3 shrink-0">
                <Button
                  variant="outline"
                  onClick={() => setSelectedCert(null)}
                  className="w-full sm:w-auto h-9 sm:h-10 px-6 rounded-xl font-semibold text-gray-700 hover:bg-gray-50 border-gray-200 text-sm"
                >
                  Close
                </Button>
                {selectedCert.download_url ? (
                  <Button
                    className="w-full sm:w-auto h-9 sm:h-10 px-6 rounded-xl font-semibold bg-gradient-to-r from-blue-600 to-purple-600 text-white hover:from-blue-700 hover:to-purple-700 shadow-md border-0 text-sm"
                    onClick={() => {
                      window.open(selectedCert.download_url, "_blank");
                    }}
                  >
                    <FiDownload className="mr-2 h-3.5 w-3.5" /> Download PDF
                  </Button>
                ) : (
                  <Button
                    className="w-full sm:w-auto h-9 sm:h-10 px-6 rounded-xl font-semibold bg-gradient-to-r from-blue-600 to-purple-600 text-white hover:from-blue-700 hover:to-purple-700 shadow-md border-0 text-sm"
                    onClick={() => {
                      handleDownload(selectedCert.name);
                    }}
                  >
                    <FiDownload className="mr-2 h-3.5 w-3.5" /> Download PDF
                  </Button>
                )}
              </div>

            </div>
          </div>
        )}

        <div className="text-center text-sm text-muted-foreground mt-12">
          <p>Certificates are generated on the server.</p>
          <p>Students can download their certificates from their dashboard.</p>
        </div>
      </div>
    </div>
  );
}