import { useState } from "react";
import { toast } from "sonner";
import { axiosInstance } from "./api";

export const useCertificatesMutations = (
  setFilterCourseId: (id: string) => void,
  setRefreshTrigger: (cb: (prev: number) => number) => void
) => {
  const [generatingBulk, setGeneratingBulk] = useState(false);
  const [generatingSingle, setGeneratingSingle] = useState(false);
  
  const [manualStudentId, setManualStudentId] = useState<string>("");
  const [manualCourseId, setManualCourseId] = useState<string>("");
  
  const [bulkCourseId, setBulkCourseId] = useState<string>("");
  const [bulkStudentIds, setBulkStudentIds] = useState<string>("");

  const generateSingleCertificate = async () => {
    const studentId = Number(manualStudentId.trim());
    const courseId = Number(manualCourseId.trim());

    if (!studentId || isNaN(studentId) || studentId <= 0) return toast.error("Please enter a valid student ID");
    if (!courseId || isNaN(courseId) || courseId <= 0) return toast.error("Please enter a valid course ID");

    setGeneratingSingle(true);

    try {
      const res = await axiosInstance.post(`/students/${studentId}/courses/${courseId}/certificate`);
      toast.success(res.data?.certificate_no ? `Certificate generated: ${res.data.certificate_no}` : "Certificate generated successfully!");
      
      if (res.data?.file_url) {
        toast.info("Certificate generated — you can now download it from student portal", { duration: 6000 });
      }

      setManualStudentId("");
      setManualCourseId("");
      setFilterCourseId(String(courseId));
      setRefreshTrigger(prev => prev + 1);
    } catch (err: any) {
      toast.error(err?.response?.data?.message || "Failed to generate certificate");
    } finally {
      setGeneratingSingle(false);
    }
  };

  const generateBulkCertificates = async () => {
    const courseIdNum = Number(bulkCourseId.trim());

    if (!courseIdNum || isNaN(courseIdNum) || courseIdNum <= 0) return toast.error("Please enter a valid course ID");

    setGeneratingBulk(true);

    try {
      let payload: any = null;
      if (bulkStudentIds.trim()) {
        const studentIds = bulkStudentIds.split(",").map((id) => Number(id.trim())).filter((id) => !isNaN(id) && id > 0);
        if (studentIds.length === 0) return toast.error("Invalid student IDs format. Use comma-separated numbers, e.g. 12,15,18");
        payload = { student_ids: studentIds };
      }

      const res = await axiosInstance.post(`/courses/${courseIdNum}/certificates/bulk`, payload);
      toast.success(`Requested: ${res.data?.requested || res.data?.total || 0} | Generated: ${res.data?.generated || 0} | Skipped: ${res.data?.skipped || res.data?.existing || 0}`);

      setBulkCourseId("");
      setBulkStudentIds("");
      setFilterCourseId(String(courseIdNum));
      setRefreshTrigger(prev => prev + 1);
    } catch (err: any) {
      console.error("Bulk generation failed:", err?.response?.data || err);
      const errorDetail = err?.response?.data;
      let msg = "Bulk generation failed";
      if (errorDetail?.detail) msg += ` - ${JSON.stringify(errorDetail.detail)}`;
      else if (errorDetail?.message) msg += ` - ${errorDetail.message}`;
      else msg += " (check console for details)";
      toast.error(msg, { duration: 8000 });
    } finally {
      setGeneratingBulk(false);
    }
  };

  const handleDownload = (studentName: string) => {
    const blob = new Blob([`Mock Certificate Data for ${studentName}\nGenerated by Laura Instructor Dashboard.`], { type: 'application/pdf' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Certificate_${studentName.replace(/\s+/g, '_')}.pdf`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
    toast.success(`Successfully downloaded certificate for ${studentName}`);
  };

  return {
    generatingSingle, setGeneratingSingle,
    generatingBulk, setGeneratingBulk,
    manualStudentId, setManualStudentId,
    manualCourseId, setManualCourseId,
    bulkCourseId, setBulkCourseId,
    bulkStudentIds, setBulkStudentIds,
    generateSingleCertificate,
    generateBulkCertificates,
    handleDownload
  };
};
